version: "3.7"
services:
    av:
        image: av
        build:
            context: .
        depends_on:
            - avdb
        restart: on-failure
        environment:
            - AVA_DATABASE_DATABASE=av
            - AVA_DATABASE_HOSTNAME=avdb
            - AVA_DATABASE_USERNAME=av
            - AVA_DATABASE_PASSWORD=av
        volumes:
            - C:\av:/opt/av
    avdb:
        container_name: avdb
        image: mariadb
        restart: on-failure
        expose:
            - "3306"
        environment:
            - MYSQL_DATABASE=av
            - MYSQL_USER=av
            - MYSQL_PASSWORD=av
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
volumes:
    av:
